# Generated by Django 6.0.6 on 2026-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('HR', 'HR'), ('Manager', 'Manager'), ('UI/UX Designer', 'UI/UX Designer')], max_length=30),
        ),
    ]
